name: Auto Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Connect to SSH and Update
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      cd /opt/web
                      git pull origin main
                      docker build -t web-app .
                      docker stop web-container || true
                      docker rm web-container || true
                      docker run -d --name web-container web-app
