name: Auto Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Connect to SSH and Update
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /opt/web
                      git pull origin main
                      docker stop web || true
                      docker rm web || true
                      docker rmi web || true
                      docker build -t web .
                      docker run -d --name web --network=host web
